name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:


    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      # - name: Login to GitHub Package Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GHCR_TOKEN }}
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          FROM_PREFIX=us-docker.pkg.dev/spinnaker-community/docker
          #FROM_PREFIX=harbor.swiftpass.cn/sp_poc
          TO_PERFIX=docker.pkg.github.com/${{ github.repository }}

          DOCKER_IMAGES=(
          igor:1.15.0-20210208200018
          clouddriver:7.3.3-20210322155326
          deck:3.6.1-20210329201325
          echo:2.16.0-20210208200018
          front50:0.26.2-20210216140019 
          gate:1.21.0-20210215200018
          orca:2.19.0-20210209140018
          rosco:0.24.0-20210210110018
          )


          for asset in "${DOCKER_IMAGES[@]}"; do
                echo $asset
                docker pull $FROM_PREFIX/$asset
                docker tag $FROM_PREFIX/$asset $TO_PERFIX/$asset 
                docker push $TO_PERFIX/$asset  
          done

          docker pull us-docker.pkg.dev/spinnaker-community/redis/redis-cluster:v2
          docker tag us-docker.pkg.dev/spinnaker-community/redis/redis-cluster:v2 $TO_PERFIX/redis-cluster:v2
          docker push $TO_PERFIX/redis-cluster:v2